name: Build and Push Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to fetch all history for tag/main comparison

      - name: Check if tag is on main
        id: check_tag
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          MAIN_COMMIT=$(git rev-parse origin/main)
          echo "Tag commit: $TAG_COMMIT"
          echo "Main commit: $MAIN_COMMIT"
          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
            echo "Tag is not on the latest commit of main. Skipping."
            exit 78
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/utdevnp/gxplorer:latest
            ghcr.io/utdevnp/gxplorer:${{ github.ref_name }} 